[options]
db_host = localhost
db_port = False
db_user = odoo
db_password = odoo
addons_path = /home/menisy/Desktop/odoo/odoo19/odoo/addons,
	/home/menisy/Desktop/odoo/odoo19/enterprise-19.0,
	/home/menisy/Desktop/odoo/odoo19/design-themes19,
	/home/menisy/Desktop/odoo/odoo19/projects/test/addons,
	/home/menisy/Desktop/odoo/odoo19/custom_addons,
default_productivity_apps = True
max_cron_threads = -1
limit_time_real = 0
//dbfilter = ^remonds$
